version: "2"

services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
    - traefik.backend=devops
    - traefik.frontend.rule=Host:devops.bieccamvd.com
    - traefik.docker.network=bridge
    - traefik.port=9000

volumes:
  portainer_data: